apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-deployment
  labels:
    app: demo
spec:
  replicas: 3
  selector: 
   matchLabels:
     app: demo
  template:
    metadata:
     name: my-pod
     labels:
       app: demo
    spec:
     containers:
      - name: my-container
        image: nginx