apiVersion: v1
kind: ReplicationController 
metadata: 
  name: my-rc
  labels: 
    app: demo
spec:
  replicas: 1
  selector:
    app: demo 
  template:
    metadata:
      name: my-pod
      labels:
        app: demo
    spec:
      containers:
       - name: my-container
         image: nginx
  
